"""index email

Revision ID: 0dad6c8372e4
Revises: 68c30264f494
Create Date: 2018-08-20 10:11:58.474348

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0dad6c8372e4'
down_revision = '68c30264f494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_email'), table_name='people')
    # ### end Alembic commands ###
