"""add rider request notes

Revision ID: 303735b04a5f
Revises: c6c4ec53a167
Create Date: 2017-10-08 15:21:20.589042

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '303735b04a5f'
down_revision = 'c6c4ec53a167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riders', 'notes')
    # ### end Alembic commands ###
