"""add hidden to destinations

Revision ID: 5a7e3f87a252
Revises: 033809bcaf32
Create Date: 2017-09-09 20:57:16.815952

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5a7e3f87a252'
down_revision = '033809bcaf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'hidden')
    # ### end Alembic commands ###
