"""add carpool from destination seed string

Revision ID: 68c30264f494
Revises: 8d1126c6edeb
Create Date: 2018-08-19 13:35:32.226367

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '68c30264f494'
down_revision = '8d1126c6edeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpools', sa.Column('from_seed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpools', 'from_seed')
    # ### end Alembic commands ###
