"""destination slug

Revision ID: 72aec41834d9
Revises: 68c30264f494
Create Date: 2018-08-28 19:40:01.313246

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '72aec41834d9'
down_revision = '68c30264f494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('slug', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_column('destinations', 'slug')
    # ### end Alembic commands ###
