"""store carpool reminder timestamp

Revision ID: 8d1126c6edeb
Revises: 303735b04a5f
Create Date: 2017-10-17 23:14:14.036486

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8d1126c6edeb'
down_revision = '303735b04a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpools', sa.Column('reminder_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpools', 'reminder_email_sent_at')
    # ### end Alembic commands ###
