"""add gender self describe

Revision ID: c6c4ec53a167
Revises: bf094584dd3c
Create Date: 2017-10-07 22:36:41.045431

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c6c4ec53a167'
down_revision = 'bf094584dd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender_self_describe', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender_self_describe')
    # ### end Alembic commands ###
