"""add destination_id to carpool

Revision ID: e356e6efd25d
Revises: 5a7e3f87a252
Create Date: 2017-09-28 20:36:42.896475

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e356e6efd25d'
down_revision = '5a7e3f87a252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpools', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key('carpools_destination_id_fkey', 'carpools', 'destinations', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carpools_destination_id_fkey', 'carpools', type_='foreignkey')
    op.drop_column('carpools', 'destination_id')
    # ### end Alembic commands ###
