"""add profile fields

Revision ID: f70474acd7db
Revises: fd3c5cf57a25
Create Date: 2017-04-16 15:34:06.822479

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f70474acd7db'
down_revision = 'fd3c5cf57a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('phone_number', sa.String(length=14), nullable=True))
    op.add_column('people', sa.Column('gender', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender')
    op.drop_column('people', 'phone_number')
    # ### end Alembic commands ###
