"""add geom carpool geoms

Revision ID: fd3c5cf57a25
Revises: 6833d8b7e849
Create Date: 2017-04-15 09:55:18.650675

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fd3c5cf57a25'
down_revision = '6833d8b7e849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpools', sa.Column('from_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    op.add_column('carpools', sa.Column('to_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpools', 'to_point')
    op.drop_column('carpools', 'from_point')
    # ### end Alembic commands ###
